name: osm_navigation
description: A new Flutter project. Trying out implementing IDP

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_polyline_points: ^2.0.0
  http: ^1.3.0
  latlong2: ^0.9.0
  provider: ^6.1.2
  webview_flutter: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/Cesium.html

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
