import 'package:freezed_annotation/freezed_annotation.dart';
import 'LocationDetail/location_detail_dto.dart';

part 'location_dto.freezed.dart';
part 'location_dto.g.dart';

/// Data Transfer Object for Location API responses
///
/// Maps exactly to the C# LocationDto from your ASP.NET Core API.
/// Used for GET requests that return complete location information.
///
/// **API Mapping:**
/// - LocationId (C# Guid) → locationId (String)
/// - Name (C# string) → name (String)
/// - Latitude (C# double) → latitude (double)
/// - Longitude (C# double) → longitude (double)
/// - Description (C# string?) → description (String?)
/// - LocationDetail (C# LocationDetailDto?) → locationDetail (LocationDetailDto?)
///
/// **Example JSON response:**
/// ```json
/// {
///   "locationId": "123e4567-e89b-12d3-a456-426614174000",
///   "name": "Rotterdam Central Station",
///   "latitude": 51.9244,
///   "longitude": 4.4777,
///   "description": "Main railway station",
///   "locationDetail": { ... }
/// }
/// ```
@freezed
abstract class LocationDto with _$LocationDto {
  const factory LocationDto({
    /// Unique identifier for the location (maps to C# Guid LocationId)
    /// Generated by backend, used for updates and references
    required String locationId,

    /// Display name of the location (maps to C# string Name)
    /// User-friendly name shown in UI
    required String name,

    /// Latitude coordinate (maps to C# double Latitude)
    /// WGS84 decimal degrees format
    required double latitude,

    /// Longitude coordinate (maps to C# double Longitude)
    /// WGS84 decimal degrees format
    required double longitude,

    /// Optional description (maps to C# string? Description)
    /// Extended information about the location
    String? description,

    /// Optional location details (maps to C# LocationDetailDto? LocationDetail)
    /// Contains supplementary information like address, contact info
    LocationDetailDto? locationDetail,
  }) = _LocationDto;

  /// Creates LocationDto from JSON response
  /// Auto-generated by Freezed for API response deserialization
  factory LocationDto.fromJson(Map<String, dynamic> json) =>
      _$LocationDtoFromJson(json);
}
