// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'route_dto.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$RouteDto {

/// Unique identifier for the route
///
/// **Type Mapping:** C# `Guid RouteId` → Dart `String`
/// **Format:** UUID v4 string (36 characters with hyphens)
/// **Usage:** Primary key for all route operations (GET, PUT, DELETE)
///
/// **Examples:**
/// - `"123e4567-e89b-12d3-a456-426614174000"`
/// - Used in API endpoints: `/api/routes/{routeId}`
///
/// **Implementation Notes:**
/// - Generated by backend on creation
/// - Immutable throughout route lifecycle
/// - Used for deep linking: `/routes/{routeId}`
 String get routeId;/// Human-readable name of the route
///
/// **Type Mapping:** C# `string Name` → Dart `String`
/// **Constraints:** 1-255 characters (enforced by backend)
/// **Usage:** Primary display text in UI lists and headers
///
/// **Examples:**
/// - `"Morning Jog Route"`
/// - `"Historic Rotterdam City Center"`
/// - `"Weekend Cycling Adventure"`
///
/// **UI Considerations:**
/// - Truncate with ellipsis for long names in list views
/// - Use as page title in route detail views
/// - Primary text for search functionality
 String get name;/// Optional detailed description of the route
///
/// **Type Mapping:** C# `string? Description` → Dart `String?`
/// **Content:** Free-form text describing route highlights, difficulty, duration
/// **Usage:** Secondary information in detail views and route cards
///
/// **Examples:**
/// - `"A peaceful 5km route along the Maas river with beautiful city views"`
/// - `"Challenging 10km route through Kralingse Bos with hill climbs"`
/// - `null` (no description provided)
///
/// **UI Considerations:**
/// - Show placeholder text when null: "No description available"
/// - Support markdown formatting in future versions
/// - Expandable text in list views for long descriptions
 String? get description;/// Identifier of the user who created this route
///
/// **Type Mapping:** C# `Guid? CreatedBy` → Dart `String?`
/// **Format:** UUID v4 string matching User entity ID
/// **Usage:** Attribution, ownership validation, user profile linking
///
/// **Security:**
/// - Used to determine edit/delete permissions
/// - Required for privacy enforcement (private routes)
/// - Links to user profile for "Created by" attribution
///
/// **Implementation:**
/// - `null` indicates system-generated or anonymous routes
/// - Cross-reference with authentication context for permissions
/// - Used in queries: "Show my routes" filtering
 String? get createdBy;/// Privacy setting determining route visibility
///
/// **Type Mapping:** C# `bool? IsPrivate` → Dart `bool?`
/// **Default:** `true` (private by default for user privacy)
/// **Usage:** Controls route discoverability and access permissions
///
/// **Behavior:**
/// - `true`: Only creator can view/edit (private routes)
/// - `false`: Publicly discoverable (community routes)
/// - `null`: Legacy data or system routes
///
/// **UI Implications:**
/// - Show privacy icon (lock/globe) in route lists
/// - Filter public routes in community/discover sections
/// - Warn users when making routes public
 bool? get isPrivate;/// Timestamp when the route was originally created
///
/// **Type Mapping:** C# `DateTime? CreatedAt` → Dart `DateTime?`
/// **Format:** UTC timestamp from backend
/// **Usage:** Sorting, filtering, and "Created on" display
///
/// **Display Examples:**
/// - List sorting: "Newest first" / "Oldest first"
/// - Detail view: "Created on May 27, 2025"
/// - Relative time: "Created 2 hours ago"
///
/// **Implementation:**
/// - Always in UTC from backend
/// - Convert to local time for display
/// - Use for data freshness indicators
 DateTime? get createdAt;/// Timestamp when the route was last modified
///
/// **Type Mapping:** C# `DateTime? UpdatedAt` → Dart `DateTime?`
/// **Format:** UTC timestamp from backend
/// **Usage:** Change tracking, sync indicators, "Last updated" display
///
/// **Business Logic:**
/// - Updated on any route modification (name, description, locations)
/// - Used for conflict resolution in offline scenarios
/// - Triggers cache invalidation in clients
///
/// **UI Applications:**
/// - Show "Recently updated" badges
/// - Sort by last activity
/// - Display modification history context
 DateTime? get updatedAt;
/// Create a copy of RouteDto
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$RouteDtoCopyWith<RouteDto> get copyWith => _$RouteDtoCopyWithImpl<RouteDto>(this as RouteDto, _$identity);

  /// Serializes this RouteDto to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is RouteDto&&(identical(other.routeId, routeId) || other.routeId == routeId)&&(identical(other.name, name) || other.name == name)&&(identical(other.description, description) || other.description == description)&&(identical(other.createdBy, createdBy) || other.createdBy == createdBy)&&(identical(other.isPrivate, isPrivate) || other.isPrivate == isPrivate)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.updatedAt, updatedAt) || other.updatedAt == updatedAt));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,routeId,name,description,createdBy,isPrivate,createdAt,updatedAt);

@override
String toString() {
  return 'RouteDto(routeId: $routeId, name: $name, description: $description, createdBy: $createdBy, isPrivate: $isPrivate, createdAt: $createdAt, updatedAt: $updatedAt)';
}


}

/// @nodoc
abstract mixin class $RouteDtoCopyWith<$Res>  {
  factory $RouteDtoCopyWith(RouteDto value, $Res Function(RouteDto) _then) = _$RouteDtoCopyWithImpl;
@useResult
$Res call({
 String routeId, String name, String? description, String? createdBy, bool? isPrivate, DateTime? createdAt, DateTime? updatedAt
});




}
/// @nodoc
class _$RouteDtoCopyWithImpl<$Res>
    implements $RouteDtoCopyWith<$Res> {
  _$RouteDtoCopyWithImpl(this._self, this._then);

  final RouteDto _self;
  final $Res Function(RouteDto) _then;

/// Create a copy of RouteDto
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? routeId = null,Object? name = null,Object? description = freezed,Object? createdBy = freezed,Object? isPrivate = freezed,Object? createdAt = freezed,Object? updatedAt = freezed,}) {
  return _then(_self.copyWith(
routeId: null == routeId ? _self.routeId : routeId // ignore: cast_nullable_to_non_nullable
as String,name: null == name ? _self.name : name // ignore: cast_nullable_to_non_nullable
as String,description: freezed == description ? _self.description : description // ignore: cast_nullable_to_non_nullable
as String?,createdBy: freezed == createdBy ? _self.createdBy : createdBy // ignore: cast_nullable_to_non_nullable
as String?,isPrivate: freezed == isPrivate ? _self.isPrivate : isPrivate // ignore: cast_nullable_to_non_nullable
as bool?,createdAt: freezed == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime?,updatedAt: freezed == updatedAt ? _self.updatedAt : updatedAt // ignore: cast_nullable_to_non_nullable
as DateTime?,
  ));
}

}


/// @nodoc
@JsonSerializable()

class _RouteDto implements RouteDto {
  const _RouteDto({required this.routeId, required this.name, this.description, this.createdBy, this.isPrivate, this.createdAt, this.updatedAt});
  factory _RouteDto.fromJson(Map<String, dynamic> json) => _$RouteDtoFromJson(json);

/// Unique identifier for the route
///
/// **Type Mapping:** C# `Guid RouteId` → Dart `String`
/// **Format:** UUID v4 string (36 characters with hyphens)
/// **Usage:** Primary key for all route operations (GET, PUT, DELETE)
///
/// **Examples:**
/// - `"123e4567-e89b-12d3-a456-426614174000"`
/// - Used in API endpoints: `/api/routes/{routeId}`
///
/// **Implementation Notes:**
/// - Generated by backend on creation
/// - Immutable throughout route lifecycle
/// - Used for deep linking: `/routes/{routeId}`
@override final  String routeId;
/// Human-readable name of the route
///
/// **Type Mapping:** C# `string Name` → Dart `String`
/// **Constraints:** 1-255 characters (enforced by backend)
/// **Usage:** Primary display text in UI lists and headers
///
/// **Examples:**
/// - `"Morning Jog Route"`
/// - `"Historic Rotterdam City Center"`
/// - `"Weekend Cycling Adventure"`
///
/// **UI Considerations:**
/// - Truncate with ellipsis for long names in list views
/// - Use as page title in route detail views
/// - Primary text for search functionality
@override final  String name;
/// Optional detailed description of the route
///
/// **Type Mapping:** C# `string? Description` → Dart `String?`
/// **Content:** Free-form text describing route highlights, difficulty, duration
/// **Usage:** Secondary information in detail views and route cards
///
/// **Examples:**
/// - `"A peaceful 5km route along the Maas river with beautiful city views"`
/// - `"Challenging 10km route through Kralingse Bos with hill climbs"`
/// - `null` (no description provided)
///
/// **UI Considerations:**
/// - Show placeholder text when null: "No description available"
/// - Support markdown formatting in future versions
/// - Expandable text in list views for long descriptions
@override final  String? description;
/// Identifier of the user who created this route
///
/// **Type Mapping:** C# `Guid? CreatedBy` → Dart `String?`
/// **Format:** UUID v4 string matching User entity ID
/// **Usage:** Attribution, ownership validation, user profile linking
///
/// **Security:**
/// - Used to determine edit/delete permissions
/// - Required for privacy enforcement (private routes)
/// - Links to user profile for "Created by" attribution
///
/// **Implementation:**
/// - `null` indicates system-generated or anonymous routes
/// - Cross-reference with authentication context for permissions
/// - Used in queries: "Show my routes" filtering
@override final  String? createdBy;
/// Privacy setting determining route visibility
///
/// **Type Mapping:** C# `bool? IsPrivate` → Dart `bool?`
/// **Default:** `true` (private by default for user privacy)
/// **Usage:** Controls route discoverability and access permissions
///
/// **Behavior:**
/// - `true`: Only creator can view/edit (private routes)
/// - `false`: Publicly discoverable (community routes)
/// - `null`: Legacy data or system routes
///
/// **UI Implications:**
/// - Show privacy icon (lock/globe) in route lists
/// - Filter public routes in community/discover sections
/// - Warn users when making routes public
@override final  bool? isPrivate;
/// Timestamp when the route was originally created
///
/// **Type Mapping:** C# `DateTime? CreatedAt` → Dart `DateTime?`
/// **Format:** UTC timestamp from backend
/// **Usage:** Sorting, filtering, and "Created on" display
///
/// **Display Examples:**
/// - List sorting: "Newest first" / "Oldest first"
/// - Detail view: "Created on May 27, 2025"
/// - Relative time: "Created 2 hours ago"
///
/// **Implementation:**
/// - Always in UTC from backend
/// - Convert to local time for display
/// - Use for data freshness indicators
@override final  DateTime? createdAt;
/// Timestamp when the route was last modified
///
/// **Type Mapping:** C# `DateTime? UpdatedAt` → Dart `DateTime?`
/// **Format:** UTC timestamp from backend
/// **Usage:** Change tracking, sync indicators, "Last updated" display
///
/// **Business Logic:**
/// - Updated on any route modification (name, description, locations)
/// - Used for conflict resolution in offline scenarios
/// - Triggers cache invalidation in clients
///
/// **UI Applications:**
/// - Show "Recently updated" badges
/// - Sort by last activity
/// - Display modification history context
@override final  DateTime? updatedAt;

/// Create a copy of RouteDto
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$RouteDtoCopyWith<_RouteDto> get copyWith => __$RouteDtoCopyWithImpl<_RouteDto>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$RouteDtoToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _RouteDto&&(identical(other.routeId, routeId) || other.routeId == routeId)&&(identical(other.name, name) || other.name == name)&&(identical(other.description, description) || other.description == description)&&(identical(other.createdBy, createdBy) || other.createdBy == createdBy)&&(identical(other.isPrivate, isPrivate) || other.isPrivate == isPrivate)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.updatedAt, updatedAt) || other.updatedAt == updatedAt));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,routeId,name,description,createdBy,isPrivate,createdAt,updatedAt);

@override
String toString() {
  return 'RouteDto(routeId: $routeId, name: $name, description: $description, createdBy: $createdBy, isPrivate: $isPrivate, createdAt: $createdAt, updatedAt: $updatedAt)';
}


}

/// @nodoc
abstract mixin class _$RouteDtoCopyWith<$Res> implements $RouteDtoCopyWith<$Res> {
  factory _$RouteDtoCopyWith(_RouteDto value, $Res Function(_RouteDto) _then) = __$RouteDtoCopyWithImpl;
@override @useResult
$Res call({
 String routeId, String name, String? description, String? createdBy, bool? isPrivate, DateTime? createdAt, DateTime? updatedAt
});




}
/// @nodoc
class __$RouteDtoCopyWithImpl<$Res>
    implements _$RouteDtoCopyWith<$Res> {
  __$RouteDtoCopyWithImpl(this._self, this._then);

  final _RouteDto _self;
  final $Res Function(_RouteDto) _then;

/// Create a copy of RouteDto
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? routeId = null,Object? name = null,Object? description = freezed,Object? createdBy = freezed,Object? isPrivate = freezed,Object? createdAt = freezed,Object? updatedAt = freezed,}) {
  return _then(_RouteDto(
routeId: null == routeId ? _self.routeId : routeId // ignore: cast_nullable_to_non_nullable
as String,name: null == name ? _self.name : name // ignore: cast_nullable_to_non_nullable
as String,description: freezed == description ? _self.description : description // ignore: cast_nullable_to_non_nullable
as String?,createdBy: freezed == createdBy ? _self.createdBy : createdBy // ignore: cast_nullable_to_non_nullable
as String?,isPrivate: freezed == isPrivate ? _self.isPrivate : isPrivate // ignore: cast_nullable_to_non_nullable
as bool?,createdAt: freezed == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime?,updatedAt: freezed == updatedAt ? _self.updatedAt : updatedAt // ignore: cast_nullable_to_non_nullable
as DateTime?,
  ));
}


}

// dart format on
