import 'package:freezed_annotation/freezed_annotation.dart';

part 'location_detail_dto.freezed.dart';
part 'location_detail_dto.g.dart';

/// Data Transfer Object for Location Detail API responses
///
/// Maps exactly to the C# LocationDetailDto from your ASP.NET Core API.
/// Contains supplementary information for a location beyond basic coordinates.
///
/// **API Mapping:**
/// - LocationDetailsId (C# Guid) → locationDetailsId (String)
/// - Address (C# string?) → address (String?)
/// - City (C# string?) → city (String?)
/// - Country (C# string?) → country (String?)
/// - ZipCode (C# string?) → zipCode (String?)
/// - PhoneNumber (C# string?) → phoneNumber (String?)
/// - Website (C# string?) → website (String?)
/// - Category (C# string?) → category (String?)
/// - Accessibility (C# string?) → accessibility (String?)
///
/// **Usage Context:**
/// - Embedded within LocationDto for GET responses
/// - Contains optional contact and categorization information
/// - All fields except locationDetailsId are optional
///
/// **Example JSON:**
/// ```json
/// {
///   "locationDetailsId": "456e7890-e89b-12d3-a456-426614174001",
///   "address": "Stationsplein 9",
///   "city": "Rotterdam",
///   "country": "Netherlands",
///   "zipCode": "3013 AK",
///   "phoneNumber": "+31 88 123 4567",
///   "website": "https://www.ns.nl",
///   "category": "Transportation",
///   "accessibility": "Wheelchair accessible"
/// }
/// ```
@freezed
abstract class LocationDetailDto with _$LocationDetailDto {
  const factory LocationDetailDto({
    /// Unique identifier for the location details (maps to C# Guid LocationDetailsId)
    /// Generated by backend, links detail record to parent location
    required String locationDetailsId,

    /// Street address (maps to C# string? Address)
    /// Full street address including number and street name
    String? address,

    /// City name (maps to C# string? City)
    /// Municipality or city where location is situated
    String? city,

    /// Country name (maps to C# string? Country)
    /// Full country name, typically "Netherlands" for Rotterdam area
    String? country,

    /// Postal/ZIP code (maps to C# string? ZipCode)
    /// Dutch postal code format (e.g., "3013 AK")
    String? zipCode,

    /// Contact phone number (maps to C# string? PhoneNumber)
    /// International format preferred (e.g., "+31 88 123 4567")
    String? phoneNumber,

    /// Website URL (maps to C# string? Website)
    /// Complete URL including protocol (http:// or https://)
    String? website,

    /// Location category/type (maps to C# string? Category)
    /// Business classification (e.g., "Restaurant", "Transportation")
    String? category,

    /// Accessibility information (maps to C# string? Accessibility)
    /// Details about wheelchair access, facilities for disabled visitors
    String? accessibility,
  }) = _LocationDetailDto;

  /// Creates LocationDetailDto from JSON response
  /// Auto-generated by Freezed for API response deserialization
  factory LocationDetailDto.fromJson(Map<String, dynamic> json) =>
      _$LocationDetailDtoFromJson(json);
}
