// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'location_detail_dto.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$LocationDetailDto {

/// Unique identifier for the location details (maps to C# Guid LocationDetailsId)
/// Generated by backend, links detail record to parent location
 String get locationDetailsId;/// Street address (maps to C# string? Address)
/// Full street address including number and street name
 String? get address;/// City name (maps to C# string? City)
/// Municipality or city where location is situated
 String? get city;/// Country name (maps to C# string? Country)
/// Full country name, typically "Netherlands" for Rotterdam area
 String? get country;/// Postal/ZIP code (maps to C# string? ZipCode)
/// Dutch postal code format (e.g., "3013 AK")
 String? get zipCode;/// Contact phone number (maps to C# string? PhoneNumber)
/// International format preferred (e.g., "+31 88 123 4567")
 String? get phoneNumber;/// Website URL (maps to C# string? Website)
/// Complete URL including protocol (http:// or https://)
 String? get website;/// Location category/type (maps to C# string? Category)
/// Business classification (e.g., "Restaurant", "Transportation")
 String? get category;/// Accessibility information (maps to C# string? Accessibility)
/// Details about wheelchair access, facilities for disabled visitors
 String? get accessibility;
/// Create a copy of LocationDetailDto
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$LocationDetailDtoCopyWith<LocationDetailDto> get copyWith => _$LocationDetailDtoCopyWithImpl<LocationDetailDto>(this as LocationDetailDto, _$identity);

  /// Serializes this LocationDetailDto to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is LocationDetailDto&&(identical(other.locationDetailsId, locationDetailsId) || other.locationDetailsId == locationDetailsId)&&(identical(other.address, address) || other.address == address)&&(identical(other.city, city) || other.city == city)&&(identical(other.country, country) || other.country == country)&&(identical(other.zipCode, zipCode) || other.zipCode == zipCode)&&(identical(other.phoneNumber, phoneNumber) || other.phoneNumber == phoneNumber)&&(identical(other.website, website) || other.website == website)&&(identical(other.category, category) || other.category == category)&&(identical(other.accessibility, accessibility) || other.accessibility == accessibility));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,locationDetailsId,address,city,country,zipCode,phoneNumber,website,category,accessibility);

@override
String toString() {
  return 'LocationDetailDto(locationDetailsId: $locationDetailsId, address: $address, city: $city, country: $country, zipCode: $zipCode, phoneNumber: $phoneNumber, website: $website, category: $category, accessibility: $accessibility)';
}


}

/// @nodoc
abstract mixin class $LocationDetailDtoCopyWith<$Res>  {
  factory $LocationDetailDtoCopyWith(LocationDetailDto value, $Res Function(LocationDetailDto) _then) = _$LocationDetailDtoCopyWithImpl;
@useResult
$Res call({
 String locationDetailsId, String? address, String? city, String? country, String? zipCode, String? phoneNumber, String? website, String? category, String? accessibility
});




}
/// @nodoc
class _$LocationDetailDtoCopyWithImpl<$Res>
    implements $LocationDetailDtoCopyWith<$Res> {
  _$LocationDetailDtoCopyWithImpl(this._self, this._then);

  final LocationDetailDto _self;
  final $Res Function(LocationDetailDto) _then;

/// Create a copy of LocationDetailDto
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? locationDetailsId = null,Object? address = freezed,Object? city = freezed,Object? country = freezed,Object? zipCode = freezed,Object? phoneNumber = freezed,Object? website = freezed,Object? category = freezed,Object? accessibility = freezed,}) {
  return _then(_self.copyWith(
locationDetailsId: null == locationDetailsId ? _self.locationDetailsId : locationDetailsId // ignore: cast_nullable_to_non_nullable
as String,address: freezed == address ? _self.address : address // ignore: cast_nullable_to_non_nullable
as String?,city: freezed == city ? _self.city : city // ignore: cast_nullable_to_non_nullable
as String?,country: freezed == country ? _self.country : country // ignore: cast_nullable_to_non_nullable
as String?,zipCode: freezed == zipCode ? _self.zipCode : zipCode // ignore: cast_nullable_to_non_nullable
as String?,phoneNumber: freezed == phoneNumber ? _self.phoneNumber : phoneNumber // ignore: cast_nullable_to_non_nullable
as String?,website: freezed == website ? _self.website : website // ignore: cast_nullable_to_non_nullable
as String?,category: freezed == category ? _self.category : category // ignore: cast_nullable_to_non_nullable
as String?,accessibility: freezed == accessibility ? _self.accessibility : accessibility // ignore: cast_nullable_to_non_nullable
as String?,
  ));
}

}


/// @nodoc
@JsonSerializable()

class _LocationDetailDto implements LocationDetailDto {
  const _LocationDetailDto({required this.locationDetailsId, this.address, this.city, this.country, this.zipCode, this.phoneNumber, this.website, this.category, this.accessibility});
  factory _LocationDetailDto.fromJson(Map<String, dynamic> json) => _$LocationDetailDtoFromJson(json);

/// Unique identifier for the location details (maps to C# Guid LocationDetailsId)
/// Generated by backend, links detail record to parent location
@override final  String locationDetailsId;
/// Street address (maps to C# string? Address)
/// Full street address including number and street name
@override final  String? address;
/// City name (maps to C# string? City)
/// Municipality or city where location is situated
@override final  String? city;
/// Country name (maps to C# string? Country)
/// Full country name, typically "Netherlands" for Rotterdam area
@override final  String? country;
/// Postal/ZIP code (maps to C# string? ZipCode)
/// Dutch postal code format (e.g., "3013 AK")
@override final  String? zipCode;
/// Contact phone number (maps to C# string? PhoneNumber)
/// International format preferred (e.g., "+31 88 123 4567")
@override final  String? phoneNumber;
/// Website URL (maps to C# string? Website)
/// Complete URL including protocol (http:// or https://)
@override final  String? website;
/// Location category/type (maps to C# string? Category)
/// Business classification (e.g., "Restaurant", "Transportation")
@override final  String? category;
/// Accessibility information (maps to C# string? Accessibility)
/// Details about wheelchair access, facilities for disabled visitors
@override final  String? accessibility;

/// Create a copy of LocationDetailDto
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$LocationDetailDtoCopyWith<_LocationDetailDto> get copyWith => __$LocationDetailDtoCopyWithImpl<_LocationDetailDto>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$LocationDetailDtoToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _LocationDetailDto&&(identical(other.locationDetailsId, locationDetailsId) || other.locationDetailsId == locationDetailsId)&&(identical(other.address, address) || other.address == address)&&(identical(other.city, city) || other.city == city)&&(identical(other.country, country) || other.country == country)&&(identical(other.zipCode, zipCode) || other.zipCode == zipCode)&&(identical(other.phoneNumber, phoneNumber) || other.phoneNumber == phoneNumber)&&(identical(other.website, website) || other.website == website)&&(identical(other.category, category) || other.category == category)&&(identical(other.accessibility, accessibility) || other.accessibility == accessibility));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,locationDetailsId,address,city,country,zipCode,phoneNumber,website,category,accessibility);

@override
String toString() {
  return 'LocationDetailDto(locationDetailsId: $locationDetailsId, address: $address, city: $city, country: $country, zipCode: $zipCode, phoneNumber: $phoneNumber, website: $website, category: $category, accessibility: $accessibility)';
}


}

/// @nodoc
abstract mixin class _$LocationDetailDtoCopyWith<$Res> implements $LocationDetailDtoCopyWith<$Res> {
  factory _$LocationDetailDtoCopyWith(_LocationDetailDto value, $Res Function(_LocationDetailDto) _then) = __$LocationDetailDtoCopyWithImpl;
@override @useResult
$Res call({
 String locationDetailsId, String? address, String? city, String? country, String? zipCode, String? phoneNumber, String? website, String? category, String? accessibility
});




}
/// @nodoc
class __$LocationDetailDtoCopyWithImpl<$Res>
    implements _$LocationDetailDtoCopyWith<$Res> {
  __$LocationDetailDtoCopyWithImpl(this._self, this._then);

  final _LocationDetailDto _self;
  final $Res Function(_LocationDetailDto) _then;

/// Create a copy of LocationDetailDto
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? locationDetailsId = null,Object? address = freezed,Object? city = freezed,Object? country = freezed,Object? zipCode = freezed,Object? phoneNumber = freezed,Object? website = freezed,Object? category = freezed,Object? accessibility = freezed,}) {
  return _then(_LocationDetailDto(
locationDetailsId: null == locationDetailsId ? _self.locationDetailsId : locationDetailsId // ignore: cast_nullable_to_non_nullable
as String,address: freezed == address ? _self.address : address // ignore: cast_nullable_to_non_nullable
as String?,city: freezed == city ? _self.city : city // ignore: cast_nullable_to_non_nullable
as String?,country: freezed == country ? _self.country : country // ignore: cast_nullable_to_non_nullable
as String?,zipCode: freezed == zipCode ? _self.zipCode : zipCode // ignore: cast_nullable_to_non_nullable
as String?,phoneNumber: freezed == phoneNumber ? _self.phoneNumber : phoneNumber // ignore: cast_nullable_to_non_nullable
as String?,website: freezed == website ? _self.website : website // ignore: cast_nullable_to_non_nullable
as String?,category: freezed == category ? _self.category : category // ignore: cast_nullable_to_non_nullable
as String?,accessibility: freezed == accessibility ? _self.accessibility : accessibility // ignore: cast_nullable_to_non_nullable
as String?,
  ));
}


}

// dart format on
