import 'package:freezed_annotation/freezed_annotation.dart';
import 'selectable_location_dto.dart';

part 'grouped_selectable_locations_response.freezed.dart';
part 'grouped_selectable_locations_response.g.dart';

/// Response DTO for the GroupedSelectableLocations API endpoint
///
/// Maps exactly to the C# Dictionary<string, List<SelectableLocationDto>> response
/// from your GetGroupedSelectableLocations endpoint. Provides an organized view
/// of locations grouped by category for selection interfaces.
///
/// **Purpose:**
/// - Organizes locations by category for UI display
/// - Enables efficient category-based filtering
/// - Reduces payload size compared to full location data
/// - Optimizes selection workflows in route creation
///
/// **API Response Structure:**
/// ```json
/// {
///   "groupedLocations": {
///     "Transportation": [
///       {"locationId": "...", "name": "Central Station", "category": "Transportation"}
///     ],
///     "Restaurants": [
///       {"locationId": "...", "name": "Cafe Rotterdam", "category": "Restaurants"}
///     ],
///     "null": [
///       {"locationId": "...", "name": "Uncategorized Location", "category": null}
///     ]
///   }
/// }
/// ```
///
/// **Usage:**
/// ```dart
/// final response = GroupedSelectableLocationsResponse.fromJson(jsonData);
/// response.groupedLocations.forEach((category, locations) {
///   print('$category: ${locations.length} locations');
/// });
/// ```
@freezed
abstract class GroupedSelectableLocationsResponse
    with _$GroupedSelectableLocationsResponse {
  const factory GroupedSelectableLocationsResponse({
    /// Dictionary of categories mapped to their selectable locations
    ///
    /// **Key:** Category name (String) - may be "null" for uncategorized locations
    /// **Value:** List of SelectableLocationDto for that category
    ///
    /// Categories are determined by the Category field in LocationDetail.
    /// Locations without categories appear under "null" key.
    required Map<String, List<SelectableLocationDto>> groupedLocations,
  }) = _GroupedSelectableLocationsResponse;

  /// Creates GroupedSelectableLocationsResponse from JSON response
  /// Auto-generated by Freezed for Dictionary<string, List<SelectableLocationDto>> structure
  factory GroupedSelectableLocationsResponse.fromJson(
    Map<String, dynamic> json,
  ) => _$GroupedSelectableLocationsResponseFromJson(json);
}
