import 'package:freezed_annotation/freezed_annotation.dart';
import 'selectable_location_dto.dart';

part 'grouped_selectable_locations_response.freezed.dart';
part 'grouped_selectable_locations_response.g.dart';

/// Response DTO for the GroupedSelectableLocations API endpoint
///
/// This matches the C# Dictionary<string, List<SelectableLocationDto>> response
/// from your GetGroupedSelectableLocations endpoint
@freezed
abstract class GroupedSelectableLocationsResponse
    with _$GroupedSelectableLocationsResponse {
  const factory GroupedSelectableLocationsResponse({
    /// Dictionary of categories mapped to their selectable locations
    /// Key: Category name (string)
    /// Value: List of SelectableLocationDto for that category
    required Map<String, List<SelectableLocationDto>> groupedLocations,
  }) = _GroupedSelectableLocationsResponse;

  /// Creates GroupedSelectableLocationsResponse from JSON response
  /// Auto-generated by Freezed - handles the Dictionary<string, List<SelectableLocationDto>> structure
  factory GroupedSelectableLocationsResponse.fromJson(
    Map<String, dynamic> json,
  ) => _$GroupedSelectableLocationsResponseFromJson(json);
}
