import 'package:freezed_annotation/freezed_annotation.dart';

part 'selectable_location_dto.freezed.dart';
part 'selectable_location_dto.g.dart';

/// Data Transfer Object for Selectable Location API responses
///
/// Maps exactly to the C# SelectableLocationDto from your ASP.NET Core API.
/// Used specifically for the GroupedSelectableLocations endpoint that provides
/// a lightweight view of locations optimized for selection UI components.
///
/// **Purpose:**
/// - Lightweight alternative to full LocationDto
/// - Optimized for dropdown/selection interfaces
/// - Groups locations by category for organized display
/// - Excludes heavy fields like coordinates and descriptions
///
/// **API Mapping:**
/// - LocationId (C# Guid) → locationId (String)
/// - Name (C# string) → name (String)
/// - Category (C# string?) → category (String?)
///
/// **Usage Context:**
/// - Embedded within GroupedSelectableLocationsResponse
/// - Used in route creation for waypoint selection
/// - Powers location picker UI components
///
/// **Example JSON in grouped response:**
/// ```json
/// {
///   "Transportation": [
///     {
///       "locationId": "123e4567-e89b-12d3-a456-426614174000",
///       "name": "Rotterdam Central Station",
///       "category": "Transportation"
///     }
///   ]
/// }
/// ```
@freezed
abstract class SelectableLocationDto with _$SelectableLocationDto {
  const factory SelectableLocationDto({
    /// Unique identifier for the location (maps to C# Guid LocationId)
    /// Used for selection and subsequent API calls
    required String locationId,

    /// Display name of the location (maps to C# string Name)
    /// User-friendly name shown in selection UI
    required String name,

    /// Location category/type (maps to C# string? Category)
    /// Used for grouping in selection interfaces, may be null for uncategorized
    String? category,
  }) = _SelectableLocationDto;

  /// Creates SelectableLocationDto from JSON response
  /// Auto-generated by Freezed for API response deserialization
  factory SelectableLocationDto.fromJson(Map<String, dynamic> json) =>
      _$SelectableLocationDtoFromJson(json);
}
