import 'package:freezed_annotation/freezed_annotation.dart';

part 'selectable_location_dto.freezed.dart';
part 'selectable_location_dto.g.dart';

/// Data Transfer Object for Selectable Location API responses
///
/// This matches the C# SelectableLocationDto from your ASP.NET Core API exactly
/// Used for the GroupedSelectableLocations endpoint that combines Location + LocationDetail data
@freezed
abstract class SelectableLocationDto with _$SelectableLocationDto {
  const factory SelectableLocationDto({
    /// Unique identifier for the location (maps to C# Guid LocationId)
    required String locationId,

    /// Name of the location (maps to C# string Name)
    required String name,

    /// Category of the location (maps to C# string? Category)
    /// Will be auto-handled by Freezed JSON generation
    String? category,
  }) = _SelectableLocationDto;

  /// Creates SelectableLocationDto from JSON response
  /// Auto-generated by Freezed - handles the API response from your ASP.NET Core backend
  factory SelectableLocationDto.fromJson(Map<String, dynamic> json) =>
      _$SelectableLocationDtoFromJson(json);
}
